version: "3"
services: 
  redis-server:
    image: "redis:latest"
    restart: "on-failure"
  flaskapp:
    build: 
      context: "./app"
      dockerfile: "Dockerfile"
    image: "flask:latest"
    ports: 
      - "3001:80"
    depends_on: 
      - "redis-server"
    restart: "on-failure"